name: docker-push

on:
  workflow_dispatch:

env:
 imageName: hueadm 

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build Image
      run: |
        docker build '${{ GITHUB.WORKSPACE }}' --file hueadm/Dockerfile --tag ${{ env.imageName }}:$(date +%s)