name: docker-push

on:
  workflow_dispatch:

runs-on: ubuntu-latest

env:
 imageName: hueadm 

jobs:

  build:
    steps:
    - uses: actions/checkout@v2
    - name: Build Image
      run: |
        docker build '${{ GITHUB.WORKSPACE }}/hueadm' --file Dockerfile --tag ${{ env.imageName }}:$(date +%s)